[package]
name = "mold-services"
description = "Native system services for mold"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
libc.workspace = true
libloading.workspace = true
mold-io.workspace = true
serde_json.workspace = true
xkbcommon.workspace = true
