# Written by wing. It records which template generated this project and what each
# file looked like at the time, so `wing template update` can tell a file you edited
# from one the template changed. Commit it.

template = "rust"
name = "morf"
generated_at = "2026-08-29T15:34:19Z"

[[files]]
path = ".env.lua"
hash = "f7ec977bf26c494fc81185d5880605c0"

[[files]]
path = ".github/workflows/release.yml"
hash = "d214e68bc9df996c81b2f2e37870ca2b"

[[files]]
path = ".github/workflows/tests.yml"
hash = "927278f544005e809480b4ef63410301"

[[files]]
path = ".gitignore"
hash = "660b0a00f1cbc3de65cbc8c39d12984e"

[[files]]
path = ".make.lua"
hash = "03f7ba57135b4231cbba7b319345aa4e"

[[files]]
path = "Cargo.toml"
hash = "dc0499ecb1a82f7695b27768838c0ffc"

[[files]]
path = "PROJECT"
hash = "7ab973cb043dbef8931d654f957364e0"

[[files]]
path = "README.md"
hash = "eb2082342236b5ddd1266450da79a154"

[[files]]
path = "examples/main.rs"
hash = "1e0ce0028275584c553bca4540c1da31"

[[files]]
path = "flake.nix"
hash = "86a46be2db3abe272da844709ce19305"

[[files]]
path = "src/lib.rs"
hash = "3b15bb715b265247ca8a968cf7ea40d6"

