[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/rendrworks/mold"

[workspace.dependencies]
bytemuck = { version = "1.25", features = ["derive"] }
cosmic-text = "=0.19.0"
jiff = "=0.2.35"
image = { version = "=0.25.10", default-features = false, features = ["jpeg", "png", "webp"] }
libc = "0.2"
libloading = "0.8"
lyon_tessellation = "=1.0.20"
luna = { git = "https://github.com/onix-os/luna", rev = "e8b7e98ec977c8973ce1a182d935d0ca1f06f465" }
pollster = "1.0"
raw-window-handle = "0.6"
resvg = { version = "=0.48.1", default-features = false, features = ["raster-images", "text"] }
rustix = { version = "1.1", features = ["event", "fs"] }
slotmap = "1.0"
serde = "1.0"
serde_json = "1.0"
svgtypes = "=0.16.1"
unicode-segmentation = "=1.13.3"
smithay-client-toolkit = "=0.21.1"
wayland-backend = { version = "=0.3.17", features = ["client_system", "rwh_06"] }
wayland-client = { version = "=0.31.15", features = ["system"] }
wayland-protocols = { version = "=0.32.13", features = ["client", "staging"] }
wayland-protocols-misc = { version = "=0.3.12", features = ["client"] }
wayland-protocols-wlr = { version = "=0.3.12", features = ["client"] }
wgpu = { version = "=30.0.1", default-features = false, features = ["std", "vulkan", "gles", "wgsl"] }
xkbcommon = "=0.8.0"
zbus = "=5.19.0"
mold-image = { path = "crates/mold-image" }
mold-desktop = { path = "crates/mold-desktop" }
mold-io = { path = "crates/mold-io" }
mold-layout = { path = "crates/mold-layout" }
mold-lua = { path = "crates/mold-lua" }
mold-menu = { path = "crates/mold-menu" }
mold-reactive = { path = "crates/mold-reactive" }
mold-region = { path = "crates/mold-region" }
mold-render = { path = "crates/mold-render" }
mold-scene = { path = "crates/mold-scene" }
mold-services = { path = "crates/mold-services" }
mold-text = { path = "crates/mold-text" }
mold-wayland = { path = "crates/mold-wayland" }

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true
