[package]
name = "mold-render"
description = "GPU renderer for mold"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bytemuck.workspace = true
mold-image.workspace = true
mold-layout.workspace = true
mold-region.workspace = true
mold-scene.workspace = true
mold-text.workspace = true
raw-window-handle.workspace = true
wgpu.workspace = true

[dev-dependencies]
pollster.workspace = true
