[package]
name = "morf-text"
description = "Text shaping and rasterization for morf"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
morf-outline.workspace = true
cosmic-text.workspace = true
morf-layout.workspace = true
morf-scene.workspace = true
signed-distance-field.workspace = true
unicode-segmentation.workspace = true
