return {
  theme = require("patin.theme"),
  widgets = {
    Button = require("patin.widgets.button"),
    Card = require("patin.widgets.card"),
    ListItem = require("patin.widgets.list_item"),
    Menu = require("patin.widgets.menu"),
    Popup = require("patin.widgets.popup"),
    ScrollView = require("patin.widgets.scroll_view"),
    Slider = require("patin.widgets.slider"),
    TextField = require("patin.widgets.text_field"),
    Toggle = require("patin.widgets.toggle"),
  },
  indicators = {
    Battery = require("patin.indicators.battery"),
    Brightness = require("patin.indicators.brightness"),
    Cellular = require("patin.indicators.cellular"),
    Clock = require("patin.indicators.clock"),
    Volume = require("patin.indicators.volume"),
    Wifi = require("patin.indicators.wifi"),
  },
  services = {
    Brightness = require("patin.services.brightness"),
    Logind = require("patin.services.logind"),
    Mpris = require("patin.services.mpris"),
    Network = require("patin.services.network"),
    Oxin = require("patin.services.oxin"),
    UPower = require("patin.services.upower"),
    Volume = require("patin.services.volume"),
  },
  shells = {
    Bar = require("patin.shells.bar"),
    Launcher = require("patin.shells.launcher"),
    LockScreen = require("patin.shells.lock"),
    NetworkSettings = require("patin.shells.network_settings"),
    Notifications = require("patin.shells.notifications"),
    Osk = require("patin.shells.osk"),
    Phone = require("patin.shells.phone"),
  },
}
