use std::collections::{HashMap, HashSet};
use std::ops::Range;
use std::time::Duration;

use crate::Value;

/// Stable identity assigned to one list-model entry.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub struct ModelId(u64);

impl ModelId {
    /// Returns the process-local numeric identity.
    pub fn raw(self) -> u64 {
        self.0
    }
}

/// One mutation emitted by a list model.
#[derive(Clone, Debug, PartialEq)]
pub enum ListChange {
    /// A new item was inserted.
    Added { index: usize, id: ModelId },
    /// An item was removed.
    Removed { index: usize, id: ModelId },
    /// An existing item changed index.
    Moved { from: usize, to: usize, id: ModelId },
    /// An item's value changed without changing identity.
    Updated { index: usize, id: ModelId },
}

#[derive(Clone, Debug)]
struct Entry {
    id: ModelId,
    value: Value,
}

/// Mutable ordered values with stable item identity and a change journal.
#[derive(Clone, Debug, Default)]
pub struct ListModel {
    next_id: u64,
    entries: Vec<Entry>,
    changes: Vec<ListChange>,
}

impl ListModel {
    /// Creates a model from ordered values.
    pub fn new(values: impl IntoIterator<Item = Value>) -> Self {
        let mut model = Self::default();
        for value in values {
            let id = model.allocate_id();
            model.entries.push(Entry { id, value });
        }
        model
    }

    /// Returns the item count.
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    /// Returns whether the model has no items.
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// Returns one item and its stable identity.
    pub fn get(&self, index: usize) -> Option<(ModelId, &Value)> {
        self.entries
            .get(index)
            .map(|entry| (entry.id, &entry.value))
    }

    /// Appends a value and returns its identity.
    pub fn push(&mut self, value: Value) -> ModelId {
        self.insert(self.entries.len(), value)
            .expect("the end index is valid")
    }

    /// Inserts a value at an index.
    pub fn insert(&mut self, index: usize, value: Value) -> Option<ModelId> {
        if index > self.entries.len() {
            return None;
        }
        let id = self.allocate_id();
        self.entries.insert(index, Entry { id, value });
        self.changes.push(ListChange::Added { index, id });
        Some(id)
    }

    /// Removes and returns a value.
    pub fn remove(&mut self, index: usize) -> Option<Value> {
        if index >= self.entries.len() {
            return None;
        }
        let entry = self.entries.remove(index);
        self.changes.push(ListChange::Removed {
            index,
            id: entry.id,
        });
        Some(entry.value)
    }

    /// Moves an item while retaining its identity.
    pub fn move_item(&mut self, from: usize, to: usize) -> bool {
        if from >= self.entries.len() || to >= self.entries.len() || from == to {
            return from == to && from < self.entries.len();
        }
        let entry = self.entries.remove(from);
        let id = entry.id;
        self.entries.insert(to, entry);
        self.changes.push(ListChange::Moved { from, to, id });
        true
    }

    /// Replaces a value while retaining its identity.
    pub fn set(&mut self, index: usize, value: Value) -> bool {
        let Some(entry) = self.entries.get_mut(index) else {
            return false;
        };
        entry.value = value;
        self.changes.push(ListChange::Updated {
            index,
            id: entry.id,
        });
        true
    }

    /// Drains mutations since the previous call.
    pub fn take_changes(&mut self) -> Vec<ListChange> {
        std::mem::take(&mut self.changes)
    }

    fn allocate_id(&mut self) -> ModelId {
        self.next_id = self.next_id.wrapping_add(1).max(1);
        ModelId(self.next_id)
    }
}

/// Delegate metadata for one visible model item.
#[derive(Clone, Debug, PartialEq)]
pub struct ViewItem {
    pub id: ModelId,
    pub index: usize,
    pub destination: f64,
}

/// Delegate transition generated by a virtual view update.
#[derive(Clone, Debug, PartialEq)]
pub enum ViewTransition {
    Populate(ViewItem),
    Add(ViewItem),
    Remove(ViewItem),
    Move {
        item: ViewItem,
        from: usize,
        target_indexes: Vec<usize>,
    },
    Displaced {
        item: ViewItem,
        from: usize,
        target_indexes: Vec<usize>,
    },
}

/// Fixed-extent vertical virtualization and transition tracker.
#[derive(Clone, Debug)]
pub struct VirtualList {
    item_extent: f64,
    viewport_extent: f64,
    offset: f64,
    overscan: usize,
    active: HashMap<ModelId, usize>,
    initialized: bool,
}

impl VirtualList {
    /// Creates a virtual list with a fixed delegate extent.
    pub fn new(item_extent: f64, viewport_extent: f64, overscan: usize) -> Option<Self> {
        (item_extent.is_finite()
            && item_extent > 0.0
            && viewport_extent.is_finite()
            && viewport_extent >= 0.0)
            .then_some(Self {
                item_extent,
                viewport_extent,
                offset: 0.0,
                overscan,
                active: HashMap::new(),
                initialized: false,
            })
    }

    /// Sets the scroll offset, clamped to the model's content range on sync.
    pub fn set_offset(&mut self, offset: f64) {
        if offset.is_finite() {
            self.offset = offset.max(0.0);
        }
    }

    /// Returns the fixed logical extent assigned to every delegate.
    pub fn item_extent(&self) -> f64 {
        self.item_extent
    }

    /// Returns indexes requiring live delegates.
    pub fn visible_range(&self, item_count: usize) -> Range<usize> {
        let maximum = (item_count as f64 * self.item_extent - self.viewport_extent).max(0.0);
        let offset = self.offset.min(maximum);
        let first = (offset / self.item_extent).floor() as usize;
        let count = (self.viewport_extent / self.item_extent).ceil() as usize + 1;
        first.saturating_sub(self.overscan)..(first + count + self.overscan).min(item_count)
    }

    /// Reconciles visible delegates and returns their transition metadata.
    pub fn sync(&mut self, model: &ListModel, changes: &[ListChange]) -> Vec<ViewTransition> {
        let range = self.visible_range(model.len());
        let visible: Vec<_> = range
            .filter_map(|index| model.get(index).map(|(id, _)| (id, index)))
            .collect();
        let next_ids: HashSet<_> = visible.iter().map(|(id, _)| *id).collect();
        let added: HashSet<_> = changes
            .iter()
            .filter_map(|change| match change {
                ListChange::Added { id, .. } => Some(*id),
                _ => None,
            })
            .collect();
        let removed: HashSet<_> = changes
            .iter()
            .filter_map(|change| match change {
                ListChange::Removed { id, .. } => Some(*id),
                _ => None,
            })
            .collect();
        let moved: HashSet<_> = changes
            .iter()
            .filter_map(|change| match change {
                ListChange::Moved { id, .. } => Some(*id),
                _ => None,
            })
            .collect();
        let target_indexes: Vec<_> = changes
            .iter()
            .map(|change| match change {
                ListChange::Added { index, .. }
                | ListChange::Removed { index, .. }
                | ListChange::Updated { index, .. } => *index,
                ListChange::Moved { to, .. } => *to,
            })
            .collect();
        let mut transitions = Vec::new();
        for (id, from) in &self.active {
            if !next_ids.contains(id) && removed.contains(id) {
                transitions.push(ViewTransition::Remove(ViewItem {
                    id: *id,
                    index: *from,
                    destination: *from as f64 * self.item_extent,
                }));
            }
        }
        for (id, index) in &visible {
            let item = ViewItem {
                id: *id,
                index: *index,
                destination: *index as f64 * self.item_extent,
            };
            match self.active.get(id) {
                None if !self.initialized => transitions.push(ViewTransition::Populate(item)),
                None if added.contains(id) => transitions.push(ViewTransition::Add(item)),
                None => transitions.push(ViewTransition::Populate(item)),
                Some(from) if from != index && moved.contains(id) => {
                    transitions.push(ViewTransition::Move {
                        item,
                        from: *from,
                        target_indexes: target_indexes.clone(),
                    });
                }
                Some(from) if from != index => transitions.push(ViewTransition::Displaced {
                    item,
                    from: *from,
                    target_indexes: target_indexes.clone(),
                }),
                _ => {}
            }
        }
        self.active = visible.into_iter().collect();
        self.initialized = true;
        transitions
    }
}

/// Inertial one-axis scrolling state used by Flickable and virtual views.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct FlickState {
    pub offset: f64,
    pub velocity: f64,
    pub minimum: f64,
    pub maximum: f64,
    pub deceleration: f64,
}

impl FlickState {
    /// Applies a direct drag delta and stops inertial motion.
    pub fn drag_by(&mut self, delta: f64) {
        self.offset = (self.offset + delta).clamp(self.minimum, self.maximum);
        self.velocity = 0.0;
    }

    /// Starts an inertial flick in property units per second.
    pub fn release(&mut self, velocity: f64) {
        self.velocity = if velocity.is_finite() { velocity } else { 0.0 };
    }

    /// Advances inertial motion and returns whether another frame is needed.
    pub fn tick(&mut self, delta: Duration) -> bool {
        if self.velocity == 0.0 {
            return false;
        }
        let seconds = delta.as_secs_f64();
        self.offset += self.velocity * seconds;
        if self.offset <= self.minimum || self.offset >= self.maximum {
            self.offset = self.offset.clamp(self.minimum, self.maximum);
            self.velocity = 0.0;
            return false;
        }
        let slowdown = self.deceleration.max(0.0) * seconds;
        if self.velocity.abs() <= slowdown {
            self.velocity = 0.0;
        } else {
            self.velocity -= slowdown.copysign(self.velocity);
        }
        self.velocity != 0.0
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn virtual_list_materializes_only_the_viewport() {
        let model = ListModel::new((0..500).map(|index| Value::Number(index as f64)));
        let mut view = VirtualList::new(40.0, 400.0, 1).unwrap();
        let transitions = view.sync(&model, &[]);

        assert_eq!(view.visible_range(model.len()), 0..12);
        assert_eq!(transitions.len(), 12);
        assert!(
            transitions
                .iter()
                .all(|transition| matches!(transition, ViewTransition::Populate(_)))
        );
    }

    #[test]
    fn model_move_marks_target_and_displaced_items() {
        let mut model = ListModel::new((0..20).map(|index| Value::Number(index as f64)));
        let mut view = VirtualList::new(20.0, 200.0, 0).unwrap();
        view.sync(&model, &[]);
        assert!(model.move_item(2, 7));
        let changes = model.take_changes();
        let transitions = view.sync(&model, &changes);

        assert!(transitions.iter().any(|transition| matches!(
            transition,
            ViewTransition::Move { from: 2, item, .. } if item.index == 7
        )));
        assert!(transitions.iter().any(|transition| matches!(
            transition,
            ViewTransition::Displaced { from: 3, item, .. } if item.index == 2
        )));
    }

    #[test]
    fn flick_can_reverse_without_resetting_position() {
        let mut flick = FlickState {
            offset: 100.0,
            velocity: 0.0,
            minimum: 0.0,
            maximum: 1_000.0,
            deceleration: 1_000.0,
        };
        flick.release(500.0);
        assert!(flick.tick(Duration::from_millis(100)));
        let before = flick.offset;
        flick.release(-500.0);
        assert_eq!(flick.offset, before);
        assert!(flick.tick(Duration::from_millis(10)));
        assert!(flick.offset < before);
    }
}
